### ISSUE TITLE
3D printer temperatures are in deg F

### ISSUE THREAD

**Issue by gth758y** [gth758y/home-assistant-wa#5]
No idea what that means. Convert to C.

**Comment by gth758y** [comment]
Changed UoM to 'C' in customize.yaml. HA was 'helpfully' converting the raw input to F based on the 'imperial' setting in configuration.yaml.

```
sensor.octoprint_actual_tool0_temp:
  unit_of_measurement: 'C'
  friendly_name: Nozzle Temperature
  icon: mdi:thermometer
  
sensor.octoprint_actual_bed_temp:
  unit_of_measurement: 'C'
  friendly_name: Nozzle Temperature
  icon: mdi:thermometer
```
