### ISSUE TITLE
3D printer expected finish time

### ISSUE THREAD

**Issue by gth758y** [gth758y/home-assistant-wa#7]
Would be nice if HA could display an expected finish time for a print.

**Comment by gth758y** [comment]
Added new sensor:

```
 - platform: template
   sensors:
     octoprint_estimated_completion_time:
       friendly_name: Octoprint ETC
       value_template: >-
         {{ (states('sensor.octoprint_time_remaining') | float + now().timestamp() | int) | timestamp_custom("%R", true) }}
```
